-- Generated by the database client.
-- Table: public.clientes

-- DROP TABLE IF EXISTS public.clientes;

CREATE TABLE IF NOT EXISTS public.clientes
(
    cliente_cod integer NOT NULL DEFAULT nextval('clientes_cliente_cod_seq'::regclass),
    cliente_nombre character varying(40) COLLATE pg_catalog."default",
    cliente_apellido character varying(40) COLLATE pg_catalog."default",
    cliente_direccion character varying(40) COLLATE pg_catalog."default",
    cliente_ciudad character varying(20) COLLATE pg_catalog."default",
    cliente_pais character varying(20) COLLATE pg_catalog."default",
    cliente_codpostal integer,
    CONSTRAINT cliente_cod PRIMARY KEY (cliente_cod)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.clientes
    OWNER to postgres;