-- Generated by the database client.
CREATE TABLE clientes(
    cod_cliente SERIAL NOT NULL,
    nombre_cliente varchar(20) NOT NULL,
    apellido_cliente varchar(20) NOT NULL,
    direccion_cliente varchar(50) NOT NULL,
    ciudad_cliente varchar(20) NOT NULL,
    codpostal_cliente integer,
    pais_cliente varchar(15) NOT NULL,
    PRIMARY KEY(cod_cliente)
);

